Create Table Employees(Emp_ID VARCHAR(20) UNIQUE, NAME VARCHAR(50),DEPARTMENT VARCHAR(20))

SELECT * FROM EMPLOYEES

ALTER TABLE EMPLOYEES
ADD COLUMN TEMPORARY_ADDRESS VARCHAR(200)

ALTER TABLE Employees
RENAME COLUMN DEPARTMENT TO DEPARTMENT_NAME

ALTER TABLE Employees
Drop Column temporary_address